### ISSUE TITLE
How exactly do I create a resource pack with custom messages?

### ISSUE THREAD

**Issue by reallydrained** [Rozmir-Rohi/loading-screen-messages#1]
I downloaded this mod thinking there would be a text file to add messages to but now I see it needs to be resource packs, how would I go about doing this?

**Comment by Rozmir-Rohi** [comment]
Please use this as a template: https://www.curseforge.com/minecraft/mc-mods/loading-screen-messages/files/5623864

**Comment by reallydrained** [comment]
> Please use this as a template: https://www.curseforge.com/minecraft/mc-mods/loading-screen-messages/files/5623864

Thank you so much! I did not see that file omg how stupid of me xD
